import type { AccommodationDef, ActivityDef } from "./bookings-data";

/** Victoria Falls & surrounds — indicative USD tiers (same shape as other destinations). */
export const VF_BOOKING_ACTIVITIES: ActivityDef[] = [
  {
    id: "rainforest-guided",
    name: "Guided tour of the Falls (Rainforest)",
    short: "Walk the rainforest paths with a guide — park entry included in most packages.",
    category: "falls",
    zimUsd: 7,
    sadcUsd: 30,
    intlUsd: 50,
  },
  {
    id: "falls-moonbow",
    name: "Lunar rainbow / full-moon viewing (when scheduled)",
    short: "Special night access windows — seasonal.",
    category: "falls",
    zimUsd: 20,
    sadcUsd: 60,
    intlUsd: 90,
  },
  {
    id: "helicopter-13min",
    name: 'Helicopter scenic flight ("Flight of Angels" style)',
    short: "Classic aerial views of the Falls & gorges.",
    category: "aerial",
    zimUsd: 150,
    sadcUsd: 150,
    intlUsd: 150,
  },
  {
    id: "microlight",
    name: "Microlight flight over Victoria Falls",
    short: "Open-cockpit adventure flight (weight & weather dependent).",
    category: "aerial",
    zimUsd: 175,
    sadcUsd: 175,
    intlUsd: 175,
  },
  {
    id: "bungee-bridge",
    name: "Bungee jump — Victoria Falls Bridge",
    short: "111 m adrenaline leap over the Zambezi gorge.",
    category: "adventure",
    zimUsd: 168,
    sadcUsd: 168,
    intlUsd: 168,
  },
  {
    id: "bridge-swing",
    name: "Bridge swing / slide combo",
    short: "Giant swing and zipline-style experiences off the bridge.",
    category: "adventure",
    zimUsd: 168,
    sadcUsd: 168,
    intlUsd: 168,
  },
  {
    id: "zambezi-rafting",
    name: "White-water rafting — Zambezi River",
    short: "Full or half-day rapids below the Falls (seasonal water levels).",
    category: "adventure",
    zimUsd: 120,
    sadcUsd: 120,
    intlUsd: 120,
  },
  {
    id: "zipline-gorge",
    name: "Zipline / flying fox across the gorge",
    short: "High-wire rush with gorge views.",
    category: "adventure",
    zimUsd: 85,
    sadcUsd: 85,
    intlUsd: 85,
  },
  {
    id: "gorge-swing",
    name: "Gorge swing",
    short: "Free-fall swing inside the Batoka Gorge.",
    category: "adventure",
    zimUsd: 95,
    sadcUsd: 95,
    intlUsd: 95,
  },
  {
    id: "sunset-cruise",
    name: "Sunset cruise on the Zambezi",
    short: "Drinks, snacks, hippos & golden light upstream of the Falls.",
    category: "cruise",
    zimUsd: 45,
    sadcUsd: 55,
    intlUsd: 65,
  },
  {
    id: "dinner-cruise",
    name: "Dinner cruise on the Zambezi",
    short: "Evening meal afloat with live entertainment on selected boats.",
    category: "cruise",
    zimUsd: 70,
    sadcUsd: 85,
    intlUsd: 95,
  },
  {
    id: "chobe-day",
    name: "Chobe National Park day trip (Botswana)",
    short: "River safari + game drive — passport required.",
    category: "daytrip",
    zimUsd: 170,
    sadcUsd: 170,
    intlUsd: 170,
  },
  {
    id: "game-drive-vf",
    name: "Game drive — Zambezi National Park",
    short: "Morning or afternoon wildlife safari near Victoria Falls.",
    category: "wildlife",
    zimUsd: 65,
    sadcUsd: 75,
    intlUsd: 85,
  },
  {
    id: "elephant-interaction",
    name: "Elephant encounter / sanctuary visit",
    short: "Ethical programmes vary — we match you to the right operator.",
    category: "wildlife",
    zimUsd: 120,
    sadcUsd: 120,
    intlUsd: 120,
  },
  {
    id: "walking-safari",
    name: "Walking safari (guided bush walk)",
    short: "Track big game on foot with an armed professional guide.",
    category: "wildlife",
    zimUsd: 75,
    sadcUsd: 85,
    intlUsd: 95,
  },
  {
    id: "cultural-village",
    name: "Cultural village & traditional dance",
    short: "History, crafts, song & dance with local communities.",
    category: "cultural",
    zimUsd: 35,
    sadcUsd: 45,
    intlUsd: 55,
  },
  {
    id: "craft-tour",
    name: "Craft market & curio shopping tour",
    short: "Curated visit with tips on fair pricing & quality.",
    category: "cultural",
    zimUsd: 15,
    sadcUsd: 25,
    intlUsd: 35,
  },
  {
    id: "high-tea-vfh",
    name: "High tea — Victoria Falls Hotel",
    short: "Colonial-era terrace views toward the spray.",
    category: "cultural",
    zimUsd: 45,
    sadcUsd: 55,
    intlUsd: 65,
  },
  {
    id: "steam-train",
    name: "Steam train / dinner bridge run (when operating)",
    short: "Heritage rail experience toward the bridge — seasonal.",
    category: "cultural",
    zimUsd: 55,
    sadcUsd: 65,
    intlUsd: 75,
  },
  {
    id: "canoeing-upper-zambezi",
    name: "Canoeing — Upper Zambezi",
    short: "Quiet channels, birds & hippos from a stable inflatable canoe.",
    category: "wildlife",
    zimUsd: 95,
    sadcUsd: 105,
    intlUsd: 115,
  },
];

export const VF_BOOKING_ACCOMMODATIONS: AccommodationDef[] = [
  {
    id: "vf-hotel",
    name: "The Victoria Falls Hotel",
    area: "Victoria Falls",
    tier: "iconic",
    fromUsd: 320,
    blurb: "Historic grande dame — lawns toward the spray.",
  },
  {
    id: "ilala-lodge",
    name: "Ilala Lodge Hotel",
    area: "Victoria Falls",
    tier: "hotel",
    fromUsd: 210,
    blurb: "Walkable to the Falls — popular mid-upper hotel.",
  },
  {
    id: "batonka",
    name: "Batonka Guest Lodge",
    area: "Victoria Falls",
    tier: "guesthouse",
    fromUsd: 165,
    blurb: "Calm garden setting, strong value & service.",
  },
  {
    id: "pioneers",
    name: "Pioneers Victoria Falls",
    area: "Victoria Falls",
    tier: "lodge",
    fromUsd: 240,
    blurb: "Boutique lodge feel close to town activity.",
  },
  {
    id: "vf-safari-lodge",
    name: "Victoria Falls Safari Lodge",
    area: "Victoria Falls",
    tier: "lodge",
    fromUsd: 260,
    blurb: "Elevated deck vulture experience & bush ambience.",
  },
  {
    id: "vf-safari-suites",
    name: "Victoria Falls Safari Suites",
    area: "Victoria Falls",
    tier: "lodge",
    fromUsd: 310,
    blurb: "Upscale sister property to Safari Lodge.",
  },
  {
    id: "stanley-livingstone",
    name: "Stanley & Livingstone Boutique Hotel",
    area: "Victoria Falls (Private Reserve)",
    tier: "lodge",
    fromUsd: 380,
    blurb: "Small luxury in a private reserve setting.",
  },
  {
    id: "matetsi",
    name: "Matetsi Victoria Falls",
    area: "Matetsi Private Game Reserve",
    tier: "iconic",
    fromUsd: 950,
    blurb: "Ultra-luxury lodge & river frontage — safari + Falls combo.",
  },
  {
    id: "sprayview",
    name: "Cresta Sprayview Hotel",
    area: "Victoria Falls",
    tier: "hotel",
    fromUsd: 95,
    blurb: "Central, dependable mid-market hotel.",
  },
  {
    id: "rainbow-vf",
    name: "Rainbow Hotel Victoria Falls",
    area: "Victoria Falls",
    tier: "hotel",
    fromUsd: 110,
    blurb: "Town-centre hotel with pool — practical base.",
  },
  {
    id: "azambezi",
    name: "A'Zambezi River Lodge",
    area: "Zambezi River",
    tier: "lodge",
    fromUsd: 175,
    blurb: "Riverside lawns & boat jetty access.",
  },
  {
    id: "explorers-village",
    name: "Shearwater Explorers Village",
    area: "Victoria Falls",
    tier: "guesthouse",
    fromUsd: 55,
    blurb: "Budget-to-mid chalets & backpacker-style hub.",
  },
  {
    id: "bayete",
    name: "Bayete Guest Lodge",
    area: "Victoria Falls",
    tier: "guesthouse",
    fromUsd: 120,
    blurb: "Friendly B&B-style lodge with pool.",
  },
  {
    id: "nkosi",
    name: "Nkosi Guest Lodge",
    area: "Victoria Falls",
    tier: "guesthouse",
    fromUsd: 95,
    blurb: "Intimate guest lodge — good for small groups.",
  },
  {
    id: "lokuthula",
    name: "Lokuthula Lodges",
    area: "Victoria Falls",
    tier: "lodge",
    fromUsd: 140,
    blurb: "Self-catering chalets on resort grounds — family favourite.",
  },
];
